-- Add missing columns to employees table
ALTER TABLE employees
  ADD COLUMN IF NOT EXISTS hourly_rate NUMERIC(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fecha_nacimiento DATE,
  ADD COLUMN IF NOT EXISTS direccion TEXT,
  ADD COLUMN IF NOT EXISTS contacto_emergencia_nombre VARCHAR(255),
  ADD COLUMN IF NOT EXISTS contacto_emergencia_telefono VARCHAR(30),
  ADD COLUMN IF NOT EXISTS eps VARCHAR(255),
  ADD COLUMN IF NOT EXISTS arl VARCHAR(255),
  ADD COLUMN IF NOT EXISTS fondo_pension VARCHAR(255),
  ADD COLUMN IF NOT EXISTS tipo_sangre VARCHAR(10),
  ADD COLUMN IF NOT EXISTS tipo_contrato VARCHAR(100),
  ADD COLUMN IF NOT EXISTS salario NUMERIC(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS jornada VARCHAR(50),
  ADD COLUMN IF NOT EXISTS fecha_ingreso DATE,
  ADD COLUMN IF NOT EXISTS fecha_retiro DATE,
  ADD COLUMN IF NOT EXISTS motivo_retiro TEXT;
