ALTER TABLE tasks ADD COLUMN IF NOT EXISTS supervisor_id UUID REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS is_favorite BOOLEAN DEFAULT false;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS estimated_minutes INTEGER;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS spent_minutes INTEGER;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS categoria VARCHAR(100);
CREATE INDEX IF NOT EXISTS idx_tasks_supervisor ON tasks(supervisor_id);
